id: pullRequestManagement.serviceLabels
name: GitOps.PullRequestServiceLabels
description: Checks the files touched by a pull request and assigns area labels.
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add labels to PRs that touch certain files
        triggerOnOwnActions: false
        if:
          - payloadType: Pull_Request
          - or:
            - isAction:
                action: Opened
            - isAction:
                action: Synchronize
          - not:
              targetsBranch:
                branch: live
        then:
          # Framework WPF
          - if:
              - filesMatchPattern:
                  pattern: '(?i).*dotnet-desktop-guide\/framework\/wpf.*'
                  matchAny: true
            then:
              - addLabel:
                  label: 'dotnet-framework/svc'
              - addLabel:
                  label: 'wpf/subsvc'

          # Framework WinForms
          - if:
              - filesMatchPattern:
                  pattern: '(?i).*dotnet-desktop-guide\/framework\/winforms.*'
                  matchAny: true
            then:
              - addLabel:
                  label: 'dotnet-framework/svc'
              - addLabel:
                  label: 'winforms/subsvc'

          # .NET WPF
          - if:
              - filesMatchPattern:
                  pattern: '(?i).*dotnet-desktop-guide\/net\/wpf.*'
                  matchAny: true
            then:
              - addLabel:
                  label: 'dotnet-desktop/svc'
              - addLabel:
                  label: 'wpf/subsvc'

          # .NET WinForms
          - if:
              - filesMatchPattern:
                  pattern: '(?i).*dotnet-desktop-guide\/net\/winforms.*'
                  matchAny: true
            then:
              - addLabel:
                  label: 'dotnet-desktop/svc'
              - addLabel:
                  label: 'winforms/subsvc'

onFailure:
onSuccess:
