revision: 6
schema-version: 5
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
      - "### Page URL\n\n(.*)"

issues:

  opened:

    # Add links to related issues if it's a doc issue
    - check:
        - type: metadata-exists
        - type: variable-exists
          name: "document_version_independent_id"
      pass:
        - link-related-issues

    # If it's an issue from docs feedback, add svc/subsvc and source labels.
    - check:
        - type: metadata-exists
      pass:
        - labels-add: ["Source - Docs.ms"]
        - svc_subsvc_labels: true

projects_v2_item:

  reordered:

    - labels-add: ["mapQuest"]

  edited:

    - check:
        - type: query
          value: "EventPayload.changes.field_value.field_name == 'Priority' || EventPayload.changes.field_value.field_name == 'Size'"
      pass:
        - labels-add: ["mapQuest"]
