revision: 4
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
     - "### Page URL\n\n(.*)"

issues:

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]

    # default for doc comment
    - check:
        - type: metadata-exists
      pass:
        - labels-add: ["Source - Docs.ms"]
        - prod_tech_labels: true

  labeled:

    # Temporary label to mark issues as updated for Quest. The label is instantly removed
    - check:
        - type: query
          value: "length(Issue.labels[?name == ':world_map: mapQUEST']) != `0`"
      pass:
        - labels-remove: [":world_map: mapQUEST"]
