revision: 3
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
     - "### Page URL\n\n(.*)"

issues:

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]

    # default for doc comment
    - check:
        - type: metadata-exists
      pass:
        - labels-add: ["Source - Docs.ms"]
        - prod_tech_labels: true

        # technology types
        - check:
            - type: metadata-comment
              name: ms.subservice
              value: "(?i)blazor$"
          pass:
            - labels-add: ["Blazor"]
            - projects-add: [35]
            - labels-remove: [":watch: Not Triaged"]
            - assignee-add: ["guardrex"]

        # Checks for specific files

        # If the word appears anywhere in the file name path, add the label
