blank_issues_enabled: false
contact_links:
  - name: .NET platform and other product feedback
    url: https://aka.ms/feedback/report?space=61
    about: Log product issues here
  - name: Microsoft Q&A - Developer Technologies
    url: https://learn.microsoft.com/answers/tags/828/developer-technologies
    about: Find answers to your technical questions about .NET
  - name: Web development tech community forums
    url: https://techcommunity.microsoft.com/category/dotnet/discussions/web-dev
    about: Discuss web development with community members
