name: Learn feedback control.
description: |
  ⛔ This template is hooked into the feedback control on the bottom of every page on the live site. It automatically fills in several fields for you. Don't use for other purposes. ⛔
body:
  - type: markdown
    attributes:
      value: "## Issue information"
  - type: markdown
    attributes:
      value: Select the issue type, and describe the issue in the text box below. Add as much detail as needed to help us resolve the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Type of issue
      options:
        - Typo
        - Code doesn't work
        - Missing information
        - Outdated article
        - Other (describe below)
    validations:
      required: true
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Description
  - type: markdown
    attributes:
      value: "## 🚧 Article information 🚧"
  - type: markdown
    attributes:
      value: "The following fields are automatically filled in for you. *Don't edit them*. Doing so will disconnect your issue from the affected article. To find other issues for ths article, search for the Document ID."
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: documentVersionIndependentId
    validations:
      required: true
    attributes:
      label: Version Independent Document ID (use to find other issues for this article)
  - type: input
    id: author
    validations:
      required: true
    attributes:
      label: Article author
      
