name: Learn feedback control.
description: |
  ⛔ This template is hooked into the feedback control on the bottom of every page on the live site. It automatically fills in several fields for you. Don't use for other purposes. ⛔
body:
  - type: markdown
    attributes:
      value: "## Issue information"
  - type: markdown
    attributes:
      value: Describe the issue in the following text box. Add as much detail as needed to help us resolve the issue.
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Description
  - type: markdown
    attributes:
      value: "## 🚧 Article information 🚧"
  - type: markdown
    attributes:
      value: "The following fields are automatically filled in. ***Don't edit them.*** Doing so will disconnect your issue from the affected article. To find other issues for this article, search for the Document ID."
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: documentVersionIndependentId
    validations:
      required: true
    attributes:
      label: Document ID
  - type: input
    id: author
    validations:
      required: true
    attributes:
      label: Article author
      
