//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Views.Book {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Index() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Views.Book.Index", typeof(Index).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;h1&gt; Book version Ajouter un contrôleur et Vue (Add a Controller and View) Resources\Views\Home\Index.fr.resx &lt;/h1&gt;.
        /// </summary>
        public static string Add_a_Controller_and_View {
            get {
                return ResourceManager.GetString("Add a Controller and View", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ajoutez un appsetting dans la configuration et y accéder à l&apos;application ..
        /// </summary>
        public static string Add_an_appsetting_in_config_and_access_it_in_app_ {
            get {
                return ResourceManager.GetString("Add an appsetting in config and access it in app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ajouter des packages de clients à l&apos;aide Bower..
        /// </summary>
        public static string Add_client_packages_using_Bower_ {
            get {
                return ResourceManager.GetString("Add client packages using Bower.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ajouter paquets en utilisant NuGet..
        /// </summary>
        public static string Add_packages_using_NuGet_ {
            get {
                return ResourceManager.GetString("Add packages using NuGet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Utilisations d&apos;application.
        /// </summary>
        public static string Application_uses {
            get {
                return ResourceManager.GetString("Application uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Apportez dans les bibliothèques de NuGet , Bower , et NPM , et automatiser les tâches à l&apos;aide Grunt ou Gulp ..
        /// </summary>
        public static string Bring_in_libraries_from_NuGet__Bower__and_npm__and_automate_tasks_using_Grunt_or_Gulp_ {
            get {
                return ResourceManager.GetString("Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or " +
                        "Gulp.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Le développement côté client.
        /// </summary>
        public static string Client_side_development {
            get {
                return ResourceManager.GetString("Client side development", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aperçu conceptuel de ce qui est ASP.NET 5.
        /// </summary>
        public static string Conceptual_overview_of_what_is_ASP_NET_5 {
            get {
                return ResourceManager.GetString("Conceptual overview of what is ASP.NET 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Développer sur différentes plateformes.
        /// </summary>
        public static string Develop_on_different_platforms {
            get {
                return ResourceManager.GetString("Develop on different platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Notions de base ASP.NET 5 tels que le démarrage et middleware..
        /// </summary>
        public static string Fundamentals_of_ASP_NET_5_such_as_Startup_and_middleware_ {
            get {
                return ResourceManager.GetString("Fundamentals of ASP.NET 5 such as Startup and middleware.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Page D&apos;accueil.
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Comment.
        /// </summary>
        public static string How_to {
            get {
                return ResourceManager.GetString("How to", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Découvrez comment la plate-forme Azure cloud de Microsoft vous permet de construire, déployer et applications Web à grande échelle ..
        /// </summary>
        public static string Learn_how_Microsoft_s_Azure_cloud_platform_allows_you_to_build__deploy__and_scale_web_apps_ {
            get {
                return ResourceManager.GetString("Learn how Microsoft\'s Azure cloud platform allows you to build, deploy, and scale" +
                        " web apps.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Apprenez à créer des applications ASP.NET qui peuvent fonctionner n&apos;importe où ..
        /// </summary>
        public static string Learn_how_to_build_ASP_NET_apps_that_can_run_anywhere_ {
            get {
                return ResourceManager.GetString("Learn how to build ASP.NET apps that can run anywhere.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Apprendre Encore Plus.
        /// </summary>
        public static string Learn_More {
            get {
                return ResourceManager.GetString("Learn More", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gérer Secrets de l&apos;utilisateur à l&apos;aide de Secret Manager..
        /// </summary>
        public static string Manage_User_Secrets_using_Secret_Manager_ {
            get {
                return ResourceManager.GetString("Manage User Secrets using Secret Manager.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Prochain.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vue D&apos;ensemble.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gestion des Paquetages.
        /// </summary>
        public static string Package_Management {
            get {
                return ResourceManager.GetString("Package Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Publier sur Microsoft Azure Web Apps.
        /// </summary>
        public static string Publish_to_Microsoft_Azure_Web_Apps {
            get {
                return ResourceManager.GetString("Publish to Microsoft Azure Web Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lire la suite sur le site de documentation.
        /// </summary>
        public static string Read_more_on_the_documentation_site {
            get {
                return ResourceManager.GetString("Read more on the documentation site", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Déployer &amp; Exécuter.
        /// </summary>
        public static string Run___Deploy {
            get {
                return ResourceManager.GetString("Run & Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exécuter des commandes dans votre bash.
        /// </summary>
        public static string Run_commands_in_your_project_json {
            get {
                return ResourceManager.GetString("Run commands in your bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exécutez votre application.
        /// </summary>
        public static string Run_your_app {
            get {
                return ResourceManager.GetString("Run your app", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exécutez votre application sur .NET de base.
        /// </summary>
        public static string Run_your_app_on__NET_Core {
            get {
                return ResourceManager.GetString("Run your app on .NET Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pages échantillon en utilisant ASP.NET MVC 6.
        /// </summary>
        public static string Sample_pages_using_ASP_NET_MVC_6 {
            get {
                return ResourceManager.GetString("Sample pages using ASP.NET MVC 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sécurité.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cibler le développement, la mise en scène ou de l&apos;environnement de production..
        /// </summary>
        public static string Target_development__staging_or_production_environment_ {
            get {
                return ResourceManager.GetString("Target development, staging or production environment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Il ya de puissantes nouvelles fonctionnalités de Visual Studio pour la création d&apos;applications web modernes ..
        /// </summary>
        public static string There_are_powerful_new_features_in_Visual_Studio_for_building_modern_web_apps_ {
            get {
                return ResourceManager.GetString("There are powerful new features in Visual Studio for building modern web apps.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Utilisez la journalisation pour enregistrer un message..
        /// </summary>
        public static string Use_logging_to_log_a_message_ {
            get {
                return ResourceManager.GetString("Use logging to log a message.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Utilisation des données.
        /// </summary>
        public static string Working_with_Data {
            get {
                return ResourceManager.GetString("Working with Data", resourceCulture);
            }
        }
    }
}
