# This is a basic workflow to help you get started with Actions

name: 'generate what''s new article'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  schedule:
  - cron: '0 0 1 * *' # The first of every month
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-what-is-new"
  create-what-is-new:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: "Print manual run reason"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Reason: ${{ github.event.inputs.reason }}"

      - uses: dotnet/docs-tools/WhatsNew.Cli@main
        env:
          GitHubKey: ${{ secrets.GITHUB_TOKEN }}
          OspoKey: ${{ secrets.OSPO_KEY }}
        with:
          owner: dotnet
          repo: AspNetCore.Docs
          savedir: './aspnetcore/whats-new'

      - name: create-pull-request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          branch: create-whatsnew-pull-request/patch
          title: "What's new article"
          commit-message: 'Bot 🤖 generated "What''s new article"'
          body: "Automated creation of What's new article."
